### ISSUE TITLE
is this repo used for anything?

### ISSUE THREAD

**Issue by tpapp** [JuliaDocs/juliadocs.github.io#1]
If not, the `https://juliadocs.github.io` url may be a bit confusing, for newbies looking for Julia's documentation.

**Comment by mortenpi** [comment]
It functions as the root page for the JuliaDocs org GitHub pages. So it should stay, but it should indeed be updated with some info.. probably with links to the JuliaDocs packages and the main manual. Thanks for bringing this up!
